In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/spam.csv')

In [ ]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [ ]:
df.isna().sum()

Category    0
Message     0
dtype: int64

In [ ]:
df['Category']=df['Category'].map({'spam':1,'ham':0})

In [ ]:
df.groupby(df['Category']).describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
0           4825   4516                             Sorry, I'll call later   
1            747    641  Please call our customer service representativ...   

               
         freq  
Category       
0          30  
1           4

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB


In [ ]:
clf=Pipeline([
    ('vect',CountVectorizer()),
    ('clf',MultinomialNB())
])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.Category,test_size=0.25,random_state=0)
clf.fit(X_train,y_train)

Pipeline(steps=[('vect', CountVectorizer()), ('clf', MultinomialNB())])

In [ ]:
clf.score(X_test,y_test)

0.9877961234745154

In [ ]:
email=["Hi How are you","You won a lottery"]
clf.predict(email)

array([0, 0])

In [ ]:
email=["You are selected for interview"]
clf.predict(email)

array([0])

In [ ]:
email=["	Please call our customer service representativ...	"]
clf.predict(email)

array([1])